# Generated by Django 3.2.18 on 2026-06-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_airavata_api', '0009_applicationsettings_queue_settings_calculator_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentErrorRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('username', models.CharField(db_index=True, max_length=64)),
                ('level', models.CharField(max_length=16)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('stacktrace', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
