# Generated by Django 3.2.18 on 2026-06-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_airavata_api', '0010_experimenterrorrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experimenterrorrecord',
            options={'ordering': ['-updated']},
        ),
        migrations.AddField(
            model_name='experimenterrorrecord',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='experimenterrorrecord',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
