#!/usr/bin/env python3
"""
Bootstrap django_airavata/settings_local.py for a fresh clone.

Idempotent. If settings_local.py already exists, this script is a no-op (respecting
any local customizations). Otherwise it waits for Keycloak to be reachable, fetches
the `pga` client secret via the admin API, and renders a dev-default settings file.

Uses stdlib only so it can run before `uv sync`.

Environment overrides (all have sensible dev defaults):
  KEYCLOAK_URL             default http://localhost:18080
  KEYCLOAK_REALM           default default
  KEYCLOAK_ADMIN_USER      default admin
  KEYCLOAK_ADMIN_PASSWORD  default admin
  AIRAVATA_API_HOST        default localhost
  AIRAVATA_API_PORT        default 9090
  GATEWAY_ID               default default
"""

import json
import os
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

KEYCLOAK_URL = os.environ.get("KEYCLOAK_URL", "http://localhost:18080")
REALM = os.environ.get("KEYCLOAK_REALM", "default")
ADMIN_USER = os.environ.get("KEYCLOAK_ADMIN_USER", "admin")
ADMIN_PASSWORD = os.environ.get("KEYCLOAK_ADMIN_PASSWORD", "admin")
AIRAVATA_API_HOST = os.environ.get("AIRAVATA_API_HOST", "localhost")
AIRAVATA_API_PORT = os.environ.get("AIRAVATA_API_PORT", "9090")
GATEWAY_ID = os.environ.get("GATEWAY_ID", "default")

SETTINGS_PATH = Path(__file__).resolve().parent.parent / "django_airavata" / "settings_local.py"


def wait_for_keycloak(timeout_s: int = 300) -> None:
    url = f"{KEYCLOAK_URL}/realms/{REALM}"
    deadline = time.time() + timeout_s
    while time.time() < deadline:
        try:
            with urllib.request.urlopen(url, timeout=5) as resp:
                if resp.status == 200:
                    return
        except (urllib.error.URLError, urllib.error.HTTPError, ConnectionError, TimeoutError):
            pass
        time.sleep(3)
    raise RuntimeError(f"Keycloak realm '{REALM}' did not become reachable at {url} within {timeout_s}s")


def fetch_admin_token() -> str:
    url = f"{KEYCLOAK_URL}/realms/master/protocol/openid-connect/token"
    body = urllib.parse.urlencode({
        "grant_type": "password",
        "client_id": "admin-cli",
        "username": ADMIN_USER,
        "password": ADMIN_PASSWORD,
    }).encode()
    req = urllib.request.Request(
        url, data=body,
        headers={"Content-Type": "application/x-www-form-urlencoded"},
    )
    with urllib.request.urlopen(req, timeout=10) as resp:
        return json.loads(resp.read())["access_token"]


def fetch_pga_secret(token: str, timeout_s: int = 120) -> str:
    """Poll until the pga client is registered (airavata-server creates it on first boot)."""
    url = f"{KEYCLOAK_URL}/admin/realms/{REALM}/clients?clientId=pga"
    deadline = time.time() + timeout_s
    while time.time() < deadline:
        req = urllib.request.Request(url, headers={"Authorization": f"Bearer {token}"})
        try:
            with urllib.request.urlopen(req, timeout=10) as resp:
                clients = json.loads(resp.read())
                if clients:
                    secret = clients[0].get("secret")
                    if secret:
                        return secret
        except (urllib.error.URLError, urllib.error.HTTPError, ConnectionError, TimeoutError):
            pass
        time.sleep(3)
    raise RuntimeError(f"pga client did not appear in realm '{REALM}' within {timeout_s}s")


SETTINGS_TEMPLATE = '''\
# Auto-generated by scripts/bootstrap_settings_local.py on first tilt up.
# Safe to edit — the bootstrap script won't overwrite an existing file.
import os
os.environ["OAUTHLIB_INSECURE_TRANSPORT"] = "1"

AIRAVATA_API_HOST = "{airavata_host}"
AIRAVATA_API_PORT = {airavata_port}
AIRAVATA_API_SECURE = False

GATEWAY_ID = "{gateway_id}"

KEYCLOAK_CLIENT_ID = "pga"
KEYCLOAK_CLIENT_SECRET = "{pga_secret}"
KEYCLOAK_AUTHORIZE_URL = "{keycloak_url}/realms/{realm}/protocol/openid-connect/auth"
KEYCLOAK_TOKEN_URL = "{keycloak_url}/realms/{realm}/protocol/openid-connect/token"
KEYCLOAK_USERINFO_URL = "{keycloak_url}/realms/{realm}/protocol/openid-connect/userinfo"
KEYCLOAK_LOGOUT_URL = "{keycloak_url}/realms/{realm}/protocol/openid-connect/logout?post_logout_redirect_uri=http://localhost:8000&client_id=pga"
KEYCLOAK_VERIFY_SSL = False

PORTAL_TITLE = "Airavata Portal"

# Vite dev mode: only the active app uses HMR on port 9000. Change VITE_DEV_APP
# and enable the matching frontend-* resource in the Tiltfile to use it.
VITE_DEV_MODE = False
# VITE_DEV_APP = "WORKSPACE"

ALLOWED_HOSTS = ["*"]
'''


def main() -> int:
    if SETTINGS_PATH.exists():
        print(f"[bootstrap] {SETTINGS_PATH} already exists — skipping", flush=True)
        return 0

    print(f"[bootstrap] waiting for Keycloak at {KEYCLOAK_URL}/realms/{REALM}", flush=True)
    wait_for_keycloak()

    print("[bootstrap] fetching admin token", flush=True)
    token = fetch_admin_token()

    print(f"[bootstrap] fetching pga client secret from realm '{REALM}'", flush=True)
    secret = fetch_pga_secret(token)

    content = SETTINGS_TEMPLATE.format(
        airavata_host=AIRAVATA_API_HOST,
        airavata_port=AIRAVATA_API_PORT,
        gateway_id=GATEWAY_ID,
        pga_secret=secret,
        keycloak_url=KEYCLOAK_URL,
        realm=REALM,
    )
    SETTINGS_PATH.write_text(content)
    print(f"[bootstrap] wrote {SETTINGS_PATH}", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
