# Generated by Django 5.1.15 on 2026-04-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_airavata_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdataarchive',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userdataarchiveentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
